### ISSUE TITLE
RFC: set initial map extent from layer

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisweb#452]
Problem: Current setting of initial map extent is HELL. Enter coordinates by hand, really?

Proposed solution: Add a label "Use layer extent" dropdown box populated with Layer names currently in Layers tab in Extent and bookmarks tab (http://maxim.nextgis.com/resource/1/update)

If a layer is chosen - populate values for Left, Right, Bottom, Up with its bbox coords.

UPD1: Only layers that have easy to get extents (internal vector layers?) can be used for starters
UPD2: ST_extent can be used to get extent for external PostGIS layers

**Comment by KolesovDmitry** [comment]
I've created a prototype. The main changes are:
 * New interface [IBboxLayer](https://github.com/nextgis/nextgisweb/blob/9f1dc4436d3cfc98a4ef5c3084f1ae9c9e4a6609/nextgisweb/layer/models.py#L20-L21). The interface promises new attribute ```extent```.
 * New button 'Set extent from layer' in GUI (see 'Layers tab in Extent and bookmarks' tab).
 * A layer can be selected by the button if it implements interface IBboxLayer.

I created implementation of the interface for VectorLayer class (https://github.com/nextgis/nextgisweb/blob/9f1dc4436d3cfc98a4ef5c3084f1ae9c9e4a6609/nextgisweb/vector_layer/model.py#L429-L467 and https://github.com/nextgis/nextgisweb/blob/9f1dc4436d3cfc98a4ef5c3084f1ae9c9e4a6609/nextgisweb/vector_layer/model.py#L682). But I think I need to create a new abstract class for example SpatialDataLayer (or something like it). I need it because current solution has some disadvantages:
 * There are several layers with extent (VectorLayers, PostgisLayers, RasterLayers). IBboxLayer must be implemented for all of them.
 * Current solution doesn't allow uniform retrieving of the extent (see https://github.com/nextgis/nextgisweb/blob/9f1dc4436d3cfc98a4ef5c3084f1ae9c9e4a6609/nextgisweb/webmap/amd/ngw-webmap/ExtentWidget.js#L52). For example if I implement the interface for PostGIS layer, I have to query  the extent using ```extent = data.postgis_layer.extent```, not ``` extent = data.vector_layer.extent```.

@dezhin, @drnextgis do you see other solutions? Do you have advises or comments?

**Comment by drnextgis** [comment]
Я немного еще подправил, посмотрите пожалуйста, можно мержить?

**Comment by drnextgis** [comment]
Closed via https://github.com/nextgis/nextgisweb/commit/447ba8a5a4a5069639d1a4ba69533dcf25d10ab4
