### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by gerbsen** [nextgis/nextgisweb#607]
Hey guys,
do you provide a docker install? I've found some folders named docker but not a real Dockerfile.

Cheers,
Daniel

**Comment by drnextgis** [comment]
Hello, the Docker support is yet experimental, not public. We can add you to Docker repo if you're willing to give feedback on that.

**Comment by gerbsen** [comment]
Oh yeah sure, I've started to build my own. Which I'm willing to share :)

**Comment by drnextgis** [comment]
@gerbsen for access to Docker repository please provide your public SSH key.

**Comment by drnextgis** [comment]
Now is open: https://github.com/nextgis/ngwdocker

**Comment by eduard-kazakov** [comment]
@jo-chemla Hey Jonathan, thanks for bringing this up, very timely.
We’re planning to deliver an easy-to-deploy Docker build for the community in Q1 this year.

**Comment by jo-chemla** [comment]
Wow that versioning infra is also great to hear. I was looking for a selfhostable alternative to [koordinates data-manager](https://koordinates.com/features/data-manager/)/portal/browser, which are also behind [kart](https://kartproject.org/) distributed version control for GIS. 

Looks like you might be targeting a full-fledged ecosystem encompassing data cataloging (nextgis-qms/stac-manager/terriamap), mapping/sharing (keplergl, dekart), eager to try this out! Thanks for reopening to keep track of the progress.

**Comment by dezhin** [comment]
It's available here: https://github.com/nextgis/nextgisweb_ce

**Comment by jo-chemla** [comment]
Impressive thanks for pointing this out! 

Testing out this built docker-image, looks like NextGIS-web bridges the gap between 

- [stac-manager](https://github.com/developmentseed/stac-manager) and [TerriaJS](https://github.com/terriajs/terriajs)/[TerriaMap](https://github.com/terriajs/terriamap) for building a geodata catalog (aggregating open-data rather than custom raster/vector sources) or full-fledged/lightweight SDI like [eoAPI](https://eoapi.dev/) for STAC, [GeoNode](https://geonode.org/) and infra GeoServer/MapServer. On the commercial side, [Koordinates](https://koordinates.com/solutions/geospatial-data-backend-for-your-apps/), [Ellipsis-Drive](https://ellipsis-drive.com/) or [Atlas.co](https://atlas.co/)
- and [keplergl](https://github.com/keplergl/kepler.gl) (for rendering/styling these datasets, building and exporting/sharing webmaps), [dekart-xyz](https://dekart.xyz/docs/about/screencast/) or commercial [Felt-Maps](https://help.felt.com/upload-anything/raster-infrastructure/organizing-your-raster-data), [FSQ Studio](https://foursquare.com/products/studio/). 

Pretty interesting!
